# Multiple Linear Regression Backward Elimination method

# import Librarys 

In [2]:
# multiple linear regression # y = bo + b1x1 + b2x2
import pandas as pd
import numpy as np
from matplotlib.pyplot import plot
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.compose import ColumnTransformer
#Building the Optimal Model using Backward Elimination
import statsmodels.regression.linear_model as smf

In [3]:
# importing data set
data=pd.read_csv('Startup_Data.csv')
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
# Getting the independent variables or split independent and dependent variable
real_x = data.iloc[:,0:4].values
real_y = data.iloc[:,4].values

# Encoding categorical data

# Encoding the Independent Variable

In [5]:

LE = LabelEncoder()
real_x[:,3] = LE.fit_transform(real_x[:,3])
real_x[:,3]
# convert data into binary format
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [3])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)

real_x = ct.fit_transform(real_x)

# Avoiding the Dummy Variable Trap

In [6]:
# Backword Eliminaion in we remove 1 column from preventing dummy variable trape
real_x = real_x[:,1:]

# Splitting the dataset into the Training set and Test set

In [7]:
traning_x,test_x,traning_y,test_y = train_test_split(real_x,real_y,test_size=0.2,random_state=0)

# Fitting Multiple Linear Regression Model to the Training Set

In [8]:
# we train the our model
MLR =  LinearRegression()
MLR.fit(traning_x,traning_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# Predicting the Test set results

In [9]:
pred_y = MLR.predict(test_x)
pred_y

array([103015.20159796, 132582.27760816, 132447.73845175,  71976.09851259,
       178537.48221054, 116161.24230163,  67851.69209676,  98791.73374688,
       113969.43533012, 167921.0656955 ])

In [10]:
# we can't get accurancy in our data because the differnce is much between actual value and predicated values
# this technique not get accurate value so we have to use other method for getting the accurancy
test_y

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [11]:
MLR.coef_ # b1 , b2 , b3 ....

array([-9.59284160e+02,  6.99369053e+02,  7.73467193e-01,  3.28845975e-02,
        3.66100259e-02])

In [12]:
MLR.intercept_  

42554.1676177692

In [13]:
# yo = b0  + b1x1 + b2x2 .. .. . BnXn  
'''
Adding a column in matrix of features: As we can check in our MLR equation (a), there is one constant term b0, 
but this term is not present in our matrix of features, so we need to add it manually. We will add a column
having values x0 = 1 associated with the constant term b0.
To add this, we will use append function of Numpy library(nm which we have already imported into our code), 
and will assign a value of 1. Below is the code for it.
'''
# Add columns of 1
real_x = np.append(arr=np.ones((50,1)).astype(int),values=real_x,axis=1)
real_x[:5,:]

array([[1, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [1, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1, 1.0, 0.0, 142107.34, 91391.77, 366168.42]], dtype=object)

In [14]:
x_opt = real_x[:,[0,1,2,3,4,5]]
x_opt = np.array(x_opt, dtype=float)
x_opt

array([[1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

In [15]:
# Multiple Linear Regression Model --- OLS
# train model
rel_ols = smf.OLS(endog=real_y,exog=x_opt).fit()
rel_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sat, 12 Sep 2020   Prob (F-statistic):           1.34e-27
Time:                        10:07:38   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.000    3.62e+04     6.4e+04
x1           198.7888   3371.007      0.059      0.953   -6595.030    6992.607
x2           -41.8870   3256.039     -0.013      0.990   -6604.003    6520.229
x3             0.8060      0.046     17.369      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# remove the Heightst value till P > SL (0.05)

In [16]:
# remove first heightst value which index is 2
x_opt = real_x[:,[0,1,3,4,5]]
x_opt = np.array(x_opt, dtype=float)
rel_ols = smf.OLS(endog=real_y,exog=x_opt).fit()
rel_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Sat, 12 Sep 2020   Prob (F-statistic):           8.49e-29
Time:                        10:07:40   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.870      7.537      0.000    3.67e+04    6.35e+04
x1           220.1585   2900.536      0.076      0.940   -5621.821    6062.138
x2             0.8060      0.046     17.606      0.000       0.714       0.898
x3            -0.0270      0.052     -0.523      0.604      -0.131       0.077
x4             0.0270      0.017      1.592      0.118      -0.007       0.061
==============================================================================
Omnibus:                       14.758   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.172
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [17]:
# stil we can't get P < SL so Again
# remove first heightst value which index is 1
x_opt = real_x[:,[0,3,4,5]]
x_opt = np.array(x_opt, dtype=float)
rel_ols = smf.OLS(endog=real_y,exog=x_opt).fit()
rel_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Sat, 12 Sep 2020   Prob (F-statistic):           4.53e-30
Time:                        10:07:41   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [18]:
# stil we can't get P < SL so Again
# remove first heightst value which index is 4
x_opt = real_x[:,[0,3,5]]
x_opt = np.array(x_opt, dtype=float)
rel_ols = smf.OLS(endog=real_y,exog=x_opt).fit()
rel_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Sat, 12 Sep 2020   Prob (F-statistic):           2.16e-31
Time:                        10:07:41   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [19]:
# stil we can't get P < SL so Again
# remove first heightst value which index is 3 (0.060)
x_opt = real_x[:,[0,3]]
x_opt = np.array(x_opt, dtype=float)
rel_ols = smf.OLS(endog=real_y,exog=x_opt).fit()
rel_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Sat, 12 Sep 2020   Prob (F-statistic):           3.50e-32
Time:                        10:07:42   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# Now We got optimum result

In [20]:
real_x = data.iloc[:,[0,3]].values
real_y = data.iloc[:,4].values
real_x

array([[165349.2, 'New York'],
       [162597.7, 'California'],
       [153441.51, 'Florida'],
       [144372.41, 'New York'],
       [142107.34, 'Florida'],
       [131876.9, 'New York'],
       [134615.46, 'California'],
       [130298.13, 'Florida'],
       [120542.52, 'New York'],
       [123334.88, 'California'],
       [101913.08, 'Florida'],
       [100671.96, 'California'],
       [93863.75, 'Florida'],
       [91992.39, 'California'],
       [119943.24, 'Florida'],
       [114523.61, 'New York'],
       [78013.11, 'California'],
       [94657.16, 'New York'],
       [91749.16, 'Florida'],
       [86419.7, 'New York'],
       [76253.86, 'California'],
       [78389.47, 'New York'],
       [73994.56, 'Florida'],
       [67532.53, 'Florida'],
       [77044.01, 'New York'],
       [64664.71, 'California'],
       [75328.87, 'Florida'],
       [72107.6, 'New York'],
       [66051.52, 'Florida'],
       [65605.48, 'New York'],
       [61994.48, 'Florida'],
       [61136.38, 'New Yor

In [21]:
LE = LabelEncoder()
real_x[:,1] = LE.fit_transform(real_x[:,1])
real_x[:,1]
# convert data into binary format
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [1])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)

real_x = ct.fit_transform(real_x)
traning_x,test_x,traning_y,test_y = train_test_split(real_x,real_y,test_size=0.2,random_state=0)

In [22]:
# we train the our model
MLR =  LinearRegression()
MLR.fit(traning_x,traning_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [23]:
pred_y = MLR.predict(test_x)
pred_y

array([104968.88239768, 133957.33622217, 135497.0349131 ,  72485.31055711,
       179362.04719701, 109820.27677127,  65657.67476855, 100480.71994663,
       111730.61659318, 169713.51906841])

In [24]:
test_y

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])